#!/bin/sh

wget https://www.encodeproject.org/files/ENCFF002CGO/@@download/ENCFF002CGO.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CGP/@@download/ENCFF002CGP.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CGQ/@@download/ENCFF002CGQ.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CGR/@@download/ENCFF002CGR.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CGS/@@download/ENCFF002CGS.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CGT/@@download/ENCFF002CGT.bed.gz
wget https://www.encodeproject.org/files/ENCFF809BIO/@@download/ENCFF809BIO.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CGU/@@download/ENCFF002CGU.bed.gz
wget https://www.encodeproject.org/files/ENCFF804OVD/@@download/ENCFF804OVD.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CGV/@@download/ENCFF002CGV.bed.gz
wget https://www.encodeproject.org/files/ENCFF515PNJ/@@download/ENCFF515PNJ.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CGW/@@download/ENCFF002CGW.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CGX/@@download/ENCFF002CGX.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHI/@@download/ENCFF002CHI.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CGY/@@download/ENCFF002CGY.bed.gz
wget https://www.encodeproject.org/files/ENCFF191HSP/@@download/ENCFF191HSP.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CGZ/@@download/ENCFF002CGZ.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHA/@@download/ENCFF002CHA.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHB/@@download/ENCFF002CHB.bed.gz
wget https://www.encodeproject.org/files/ENCFF939TZS/@@download/ENCFF939TZS.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHC/@@download/ENCFF002CHC.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHD/@@download/ENCFF002CHD.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHE/@@download/ENCFF002CHE.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHF/@@download/ENCFF002CHF.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHG/@@download/ENCFF002CHG.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHJ/@@download/ENCFF002CHJ.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHK/@@download/ENCFF002CHK.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHL/@@download/ENCFF002CHL.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHM/@@download/ENCFF002CHM.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHO/@@download/ENCFF002CHO.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHP/@@download/ENCFF002CHP.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHR/@@download/ENCFF002CHR.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHH/@@download/ENCFF002CHH.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHS/@@download/ENCFF002CHS.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHT/@@download/ENCFF002CHT.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHU/@@download/ENCFF002CHU.bed.gz
wget https://www.encodeproject.org/files/ENCFF374VLY/@@download/ENCFF374VLY.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHV/@@download/ENCFF002CHV.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHQ/@@download/ENCFF002CHQ.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHW/@@download/ENCFF002CHW.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHX/@@download/ENCFF002CHX.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHY/@@download/ENCFF002CHY.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CHZ/@@download/ENCFF002CHZ.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CIA/@@download/ENCFF002CIA.bed.gz
wget https://www.encodeproject.org/files/ENCFF144PGS/@@download/ENCFF144PGS.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CIB/@@download/ENCFF002CIB.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CIC/@@download/ENCFF002CIC.bed.gz
wget https://www.encodeproject.org/files/ENCFF694OTE/@@download/ENCFF694OTE.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CID/@@download/ENCFF002CID.bed.gz
wget https://www.encodeproject.org/files/ENCFF002CIE/@@download/ENCFF002CIE.bed.gz

